server:
  port: 8080
  servlet:
    session:
      timeout: 480m

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v1/api-docs

storage:
  file:
    location: c:/temp/files
  image:
    location: c:/temp/images

env: local

aws:
  s3:
    region: ap-northeast-2
    bucket:
      name: dummy
    credentials:
      access:
        key: dummy
      secret:
        key: dummy